title: Page

columns:
  main:
    width: 2/3
    fields:
      subheading:
        label: Subheading
        type: text
        validate: notEmpty
      cover:
        label: Cover image
        type: files
        multiple: false
        layout: cards
        size: large
        uploads:
          template: image
      text:
        type: blocks
        label: Content

  sidebar:
    width: 1/3
    sections:
      meta:
        type: fields
        fields:
          width:
            type: toggle
            label: Desktop width
            text:
              - "Narrow"
              - "Wide"
      pages:
        type: pages
        template: default
      files:
        type: files
